server:
  port: 8081
spring:
  application:
    # 应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://111.229.151.43:3306/swagger?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: '*VYKmhufX%Ze5S!=QCq^KYuP'
#localhost
#      url: jdbc:mysql://127.0.0.1:3306/swagger?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: abcd@1234
#追加swagger3相关配置项
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


# 启用或关闭swagger
springfox:
  documentation:
    #解决打开swagger后api-doc无法正确显示的问题
    open-api:
      v3:
        path: /${spring.application.name}/v3/api-docs
    enabled: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
#      id-type: ASSIGN_ID
reggie:
  path: D:\img\
# springdoc-openapi项目配置
#swaggerURL http://localhost:8081/swagger-ui/index:
  html#/:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
